### ISSUE TITLE
update main.tf for both modules "required_version" to use >=

### ISSUE THREAD

**Issue by darpham** [gruntwork-io/terragrunt-infrastructure-modules-example#16]
Ran into an issue while using the latest 12.26 terraform version.
As the comment above stated, any terraform version above 12.x should work fine.
`  # The latest version of Terragrunt (v0.19.0 and above) requires Terraform 0.12.0 or above.`

```
Error: Unsupported Terraform Core version

This configuration does not support Terraform version 0.12.26. To proceed,
either choose another supported Terraform version or update the root module's
version constraint. Version constraints are normally set for good reason, so
updating the constraint may lead to other errors or unexpected behavior.
```

**Comment by robmorgan** [comment]
This issue will be solved by: https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/pull/19. You will no longer be able to use Terraform 0.12.x and must instead use the explicit supported Terraform version which is 0.13.3 at the time of writing.
