### ISSUE TITLE
Terragrunt validate failing

### ISSUE THREAD

**Issue by prasadm1983** [gruntwork-io/terragrunt-infrastructure-modules-example#17]
Hi Getting below issue while running terragrunt validate-all. Not getting any clue .
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Duplicate backend configuration

  on main.tf line 15, in terraform:
  15:   backend "s3" {}

A module may have only one backend configuration. The backend was previously
configured at backend.tf:3,3-15.

Error: Duplicate provider configuration

  on provider.tf line 2:
   2: provider "aws" {

A default (non-aliased) provider configuration for "aws" was already given at
main.tf:9,1-15. If multiple configurations are required, set the "alias"
argument for alternative configurations.

**Comment by brikis98** [comment]
As the error indicates, it sounds like you have two `backend { ... }` and two `provider "aws" { ... }` blocks in your code. Without seeing your code, it's hard to say more!

**Comment by yorinasub17** [comment]
I think I know what is going on actually. The example `terragrunt-infrastructure-live-example` repo is pointing to a release (`v0.1.0`), but the code has been updated since then to use `generate` blocks. We need to cut a new release and update the live example to point to that.

**Comment by yorinasub17** [comment]
Ok cut a new release (`v0.2.0`) and updated the live config
