### ISSUE TITLE
Why does module contain Terraform backend declaration?

### ISSUE THREAD

**Issue by Tensho** [gruntwork-io/terragrunt-infrastructure-modules-example#6]
I wonder what is the reason to put Terraform backend declaration **inside the module**? It's reasonable to assume user would expect to see backend declaration in the environment area (prod, stage, qa). Module should not care what kind of backend is in use. I understand `terraform.tfvars` can't hold something except variables, and backend should be specified somewhere. However, `main.tf` or `backend.tf` inside the environment folder is a more appropriate place. Consider the next folder layouts:
```
GOOD

prod
  terraform.tfvars
  backend.tf
stage
  terraform.tfvars
  backend.tf
```
```
BETTER

backend.tf # usually we use one backend for all kind of TF states
prod
  terraform.tfvars
  backend.tf # but you may always override the global value in the downstream
stage
  terraform.tfvars
```
Ideally, Terragrunt could infer `main.tf`/`backend.tf` file with the corresponding Terraform code from `terragrunt.remote_state.backend` config in `terraform.tfvars` file:
```
BEST

terraform.tfvars # infer terraform backend code from `terragrunt.remote_state.backend` config  and copy it to `.terragrunt-cache` folder
prod
  terraform.tfvars # you may always override the global `terragrunt.remote_state.backend` value in the downstream
stage
  terraform.tfvars
```

**Comment by brikis98** [comment]
Terragrunt can't infer `backend` or `provider` settings for you. All Terragrunt does is run various Terraform commands and pass various CLI args to make things more convenient. I'm not sure we should head into the realm of code generation, as that can get quite complicated to do in a truly generic way. If you wish to create `backend` or `provider` configurations for your own modules on the fly, you may want to look into [hooks](https://github.com/gruntwork-io/terragrunt#before-and-after-hooks).

**Comment by Tensho** [comment]
@brikis98 Thank you for the answer 🙇  @antonbabenko recently showed pretty the same implementation in his reference repo [`terragrunt-reference-architecture`](https://github.com/antonbabenko/terragrunt-reference-architecture) as you suggested. 

- [Hook](https://github.com/antonbabenko/terragrunt-reference-architecture/blob/master/acme-prod/terraform.tfvars#L23)
- [Common provider & remote state backend definition](https://github.com/antonbabenko/terragrunt-reference-architecture/blob/master/common/main_providers.tf)

TBH, I'd consider that as a bit of code generation 😺  Until Terragrunt stuff would be merged in a someway to Terrafom (and I believe it should be), don't you think Terragrunt should handle common Terraform code (not only vars) out of the box **without hooks**? In this case, Terragrunt doesn't need to care about any configuration inference, only compile (put the stuff to `.terragrunt-cache` directory) some kind of `common.tf` or `terragrunt.tf` files. User will be responsible for particular TF state backend configuration according to his/her requirements..

**Comment by brikis98** [comment]
> TBH, I'd consider that as a bit of code generation

It is. But it's much easier for you to do code generation for your specific use case than it is for Terragrunt to try to do it in a generic way that can fit all use cases. 

> don't you think Terragrunt should handle common Terraform code (not only vars) out of the box without hooks?

If it can be done without massively increasing complexity, sure. But generating code often gets  complicated quickly. E.g., For generating the `backend` config, where should the generated code go? If, say, `backend.tf`, what if that file already exists? Or, what if in another file, the user already has a `terraform { ... }` block, do we then have to merge it? What if the user has `backend { ... }` block in some code but not others, do we need to have conditional generation? How do we keep up to date with Terraform changes? And the `backend` config is much easier than the `provider` config, which Terragrunt doesn't currently touch at all, and which has way more flexibility (e.g., multiple providers with aliases, dozens of provider settings, etc).

**Comment by Tensho** [comment]
Thank you 🙇
